server.port=8092
spring.application.name=propertyview

# TODO(ania): move to env vars
# http://localhost:8080/h2-console
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.password=password
spring.datasource.url=jdbc:h2:/tmp/propertyview;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
