server.port=8092
spring.application.name=propertyview

# TODO(ania): move to env vars
# http://localhost:8080/h2-console
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.password=password
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.datasource.url=jdbc:h2:file:/data/demo
